/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hu.szamalk.graph;

import hu.szamalk.main.MainGUI;

/**
 *
 * @author Roland
 */
public class CsatolmanyNelkuliNevRekord extends javax.swing.JPanel {
    private int nevHely;
    /**
     * Creates new form CsatolmanyNelkuliNevRekord
     */
    public CsatolmanyNelkuliNevRekord(int nevHely) {
        initComponents();
        this.nevHely = nevHely;
        TF_nev.setText(MainGUI.nevEmailMunkaviszony[nevHely][0]);
        TF_email.setText(MainGUI.nevEmailMunkaviszony[nevHely][1]);
        La_sorszam.setText(MainGUI.sorszam[nevHely] + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TF_nev = new javax.swing.JTextField();
        Chk_kijelol = new javax.swing.JCheckBox();
        TF_email = new javax.swing.JTextField();
        Bt_torol = new javax.swing.JButton();
        La_sorszam = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(424, 80));
        setPreferredSize(new java.awt.Dimension(316, 63));

        TF_nev.setEditable(false);
        TF_nev.setText("Szabó Roland");
        TF_nev.setMaximumSize(new java.awt.Dimension(300, 2147483647));
        TF_nev.setMinimumSize(new java.awt.Dimension(84, 22));
        TF_nev.setPreferredSize(new java.awt.Dimension(100, 22));

        Chk_kijelol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chk_kijelolActionPerformed(evt);
            }
        });

        TF_email.setEditable(false);
        TF_email.setText("rolandszb111@gmail.com");
        TF_email.setMaximumSize(new java.awt.Dimension(288, 2147483647));
        TF_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_emailActionPerformed(evt);
            }
        });

        Bt_torol.setText("Töröl");
        Bt_torol.setEnabled(false);

        La_sorszam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        La_sorszam.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Chk_kijelol)
                        .addGap(12, 12, 12)
                        .addComponent(TF_nev, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(La_sorszam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TF_email, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(Bt_torol)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Chk_kijelol, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_nev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(La_sorszam, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(TF_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Bt_torol)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TF_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_emailActionPerformed

    }//GEN-LAST:event_TF_emailActionPerformed

    private void Chk_kijelolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chk_kijelolActionPerformed
        MainGUI.nevetKijelol[nevHely] = Chk_kijelol.isSelected();
        MainGUI.notice.doUpdate();
    }//GEN-LAST:event_Chk_kijelolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_torol;
    private javax.swing.JCheckBox Chk_kijelol;
    private javax.swing.JLabel La_sorszam;
    private javax.swing.JTextField TF_email;
    private javax.swing.JTextField TF_nev;
    // End of variables declaration//GEN-END:variables
}
