/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hu.szamalk.graph;

import hu.szamalk.main.MainGUI;
import java.awt.Component;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JComponent;

/**
 *
 * @author Roland
 */
public class LevelRekord extends javax.swing.JPanel {
    private int nevHely;
    /**
     * Creates new form Tar
     */
    public LevelRekord(int nevHely, int[] csatolmanyok) {
        initComponents();
        Chk_kijelol.setSelected(MainGUI.nevetKijelol[nevHely]);
        TF_nev.setText(MainGUI.nevEmailMunkaviszony[nevHely][0]);
        TF_email.setText(MainGUI.nevEmailMunkaviszony[nevHely][1]);
        La_sorszam.setText(MainGUI.sorszam[nevHely] + "");
        Cb_csatolmanyok.removeAllItems();
        for (int csatolmany : csatolmanyok) {
            Cb_csatolmanyok.addItem(MainGUI.FileList[csatolmany]);
        }
        La_csatolmanyokSzama.setText(csatolmanyok.length + "");
        this.nevHely = nevHely;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Chk_kijelol = new javax.swing.JCheckBox();
        TF_nev = new javax.swing.JTextField();
        TF_email = new javax.swing.JTextField();
        La_csatolmanyokSzama = new javax.swing.JLabel();
        Cb_csatolmanyok = new javax.swing.JComboBox<>();
        Bt_kuld = new javax.swing.JButton();
        Bt_torol = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        Bt_nameEdit = new javax.swing.JButton();
        La_sorszam = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 60));
        setMinimumSize(new java.awt.Dimension(0, 60));
        setPreferredSize(new java.awt.Dimension(587, 60));

        Chk_kijelol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chk_kijelolActionPerformed(evt);
            }
        });

        TF_nev.setEditable(false);
        TF_nev.setText("Szabó Roland");

        TF_email.setEditable(false);
        TF_email.setText("rolandszb111@gmail.com");
        TF_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_emailActionPerformed(evt);
            }
        });

        La_csatolmanyokSzama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        La_csatolmanyokSzama.setText("2");

        Cb_csatolmanyok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nagy Barbara Margit 1_202309_98_20_003_00_MunkaBerjegyzek.pdf", "Nagy Barbara Margit 1_202309_98_20_004_00_MunkaBerjegyzek.pdf" }));
        Cb_csatolmanyok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_csatolmanyokActionPerformed(evt);
            }
        });

        Bt_kuld.setText("Küld");
        Bt_kuld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_kuldActionPerformed(evt);
            }
        });

        Bt_torol.setText("Inaktivál");
        Bt_torol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_torolActionPerformed(evt);
            }
        });

        Bt_nameEdit.setText("Név szerkesztése");
        Bt_nameEdit.setEnabled(false);

        La_sorszam.setText("1");
        La_sorszam.setMaximumSize(new java.awt.Dimension(16, 16));
        La_sorszam.setMinimumSize(new java.awt.Dimension(16, 16));
        La_sorszam.setPreferredSize(new java.awt.Dimension(16, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Chk_kijelol)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cb_csatolmanyok, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(TF_nev, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(La_sorszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(TF_email, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(La_csatolmanyokSzama, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bt_nameEdit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Bt_kuld)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bt_torol)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_nev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt_kuld)
                    .addComponent(Bt_torol)
                    .addComponent(La_sorszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cb_csatolmanyok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(La_csatolmanyokSzama)
                            .addComponent(Bt_nameEdit)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
            .addComponent(Chk_kijelol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Cb_csatolmanyokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_csatolmanyokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cb_csatolmanyokActionPerformed

    private void TF_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_emailActionPerformed

    private void Bt_kuldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_kuldActionPerformed
        if(MainGUI.notice != null) MainGUI.notice.doKuld(nevHely);
    }//GEN-LAST:event_Bt_kuldActionPerformed

    private void Bt_torolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_torolActionPerformed
        MainGUI.inaktivalt[nevHely] = true;
        if(MainGUI.notice != null){ 
            System.out.println(nevHely);
            MainGUI.notice.doUpdate();
        }
    }//GEN-LAST:event_Bt_torolActionPerformed

    private void Chk_kijelolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chk_kijelolActionPerformed
        MainGUI.nevetKijelol[nevHely] = Chk_kijelol.isSelected();
    }//GEN-LAST:event_Chk_kijelolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_kuld;
    private javax.swing.JButton Bt_nameEdit;
    private javax.swing.JButton Bt_torol;
    private javax.swing.JComboBox<String> Cb_csatolmanyok;
    private javax.swing.JCheckBox Chk_kijelol;
    private javax.swing.JLabel La_csatolmanyokSzama;
    private javax.swing.JLabel La_sorszam;
    private javax.swing.JTextField TF_email;
    private javax.swing.JTextField TF_nev;
    private javax.swing.Box.Filler filler1;
    // End of variables declaration//GEN-END:variables
}
